name 'lesaux-graphite'
version '0.0.1'
source 'git clone https://github.com/lesaux/puppet-graphite.git'
author 'adapted from Daniel Werdermann by Pierig Le Saux'
license 'Mozilla Public License Version 2.0'
summary 'Graphite Monitoring Module'
description 'This module installs and makes advanced configs for graphite, with carbon and whisper'
project_page 'https://github.com/lesaux/puppet-graphite'

dependency   'puppetlabs/stdlib', '>= 3.2.0'
